# Generated by Django 6.0.6 on 2026-06-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterModelOptions(
            name='buyurtma',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='haydovchi',
            options={'verbose_name': 'Haydovchi', 'verbose_name_plural': 'Haydovchilar'},
        ),
        migrations.AlterModelOptions(
            name='mijoz',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='suv',
            options={'verbose_name': 'Suv', 'verbose_name_plural': 'Suvlar'},
        ),
        migrations.AddField(
            model_name='haydovchi',
            name='ism_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='haydovchi',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='haydovchi',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='ism_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='ism_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='ism_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='manzil_en',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='manzil_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='manzil_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='suv',
            name='batafsil_en',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='suv',
            name='batafsil_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='suv',
            name='batafsil_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='suv',
            name='brend_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='suv',
            name='brend_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='suv',
            name='brend_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.CharField(default='09:00 - 18:00', max_length=50, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='yosh',
            field=models.PositiveIntegerField(default=18, verbose_name='Yosh'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='haydovchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.haydovchi', verbose_name='Haydovchi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='mijoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mijoz', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='miqdor',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='suv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suv', verbose_name='Suv'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='umumiy_narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='haydovchi',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='haydovchi',
            name='smena',
            field=models.CharField(choices=[('ertalab', 'Ertalab (06:00-14:00)'), ('kunduz', 'Kunduz (14:00-22:00)'), ('kechasi', 'Kechasi (22:00-06:00)')], max_length=20, verbose_name='Smena'),
        ),
        migrations.AlterField(
            model_name='haydovchi',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='manzil',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='qarz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='suv',
            name='batafsil',
            field=models.TextField(blank=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='suv',
            name='brend',
            field=models.CharField(max_length=100, verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='suv',
            name='litr',
            field=models.FloatField(verbose_name='Litr'),
        ),
        migrations.AlterField(
            model_name='suv',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
    ]
